### ISSUE TITLE
ossible to start the demo project

### ISSUE THREAD

**Issue by jul6art** [kamilmysliwiec/nest#105]
Hi, i run the simple commands 
```

git clone ...
cd project
npm install 
npm run start
```

but that doesn't work

My configuration:
```
windows 8.1
npm 5.1.0
node 6.11.0
```

The error trace
```
> nest-typescript-starter@1.0.0 start C:\Users\VanIllaSkyPE\Documents\devoirs\we
b developer\En cours\Nest\project
> node index.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'ts-node/register'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\VanIllaSkyPE\Documents\devoirs\web developer
\En cours\Nest\project\index.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-typescript-starter@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-typescript-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VanIllaSkyPE\AppData\Roaming\npm-cache\_logs\2017-07-09T14
_46_24_140Z-debug.log
```

**Comment by jul6art** [comment]
up

**Comment by jul6art** [comment]
Responding myself, set in package.json

ts-node version to ~3.2.0
typescript version to ~2.3.4

And it runs

**Comment by kamilmysliwiec** [comment]
Hey @jul6art,
Awesome. In the nearest release both `ts-node` and `typescript` packages will be updated.
