### ISSUE TITLE
Middleware consumer throws error

### ISSUE THREAD

**Issue by benbayard** [kamilmysliwiec/nest#112]
I am getting this error on `@nestjs/core@5.0.3` NOT `@5.0.1`
```
[Nest] 10519   - 2017-7-15 11:53:19   [ExceptionHandler] Cannot read property 'resolve' of null
TypeError: Cannot read property 'resolve' of null
    at Function.setupHandler (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:68:48)
    at middlewares.map (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:64:18)
    at Array.map (native)
    at Function.setupRouteMiddleware (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:57:21)
    at forRoutes.forEach (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:51:18)
    at Array.forEach (native)
    at Function.setupMiddlewareConfig (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:50:19)
    at forEach (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:44:22)
    at Array.forEach (native)
    at configs.forEach (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:43:32)
    at Map.forEach (native)
    at Function.setupMiddlewares (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/middlewares/middlewares-module.js:42:17)
    at NestApplication.setupMiddlewares (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/nest-application.js:81:48)
    at NestApplication.init (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/nest-application.js:34:14)
    at NestApplication.listen (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/nest-application.js:55:39)
    at exceptions_zone_1.ExceptionsZone.run (/home/bbayard/github.com/teamtwofer/dinosaurinspector/node_modules/@nestjs/core/nest-factory.js:62:48)

```

when I use this code:

```
@Middleware()
export class AuthMiddleware implements NestMiddleware {
  constructor(private service: UserService) {}

  @autobind
  resolve() {
  }
}
export class UserModule {
  configure(consumer: MiddlewaresConsumer) {
    consumer.apply(AuthMiddleware).forRoutes(
      {
        method: RequestMethod.GET,
        path: 'user',
      },
      {
        method: RequestMethod.DELETE,
        path: 'user/:id',
      }
    );
  }
}
```

**Comment by kamilmysliwiec** [comment]
Hi @benbayard,
The v3.0.1 is the latest stable version.

**Comment by benbayard** [comment]
That was my solution as well, but still wanted to report the error!

**Comment by kamilmysliwiec** [comment]
Got it, thanks for reporting. The beta version would be available this month, so stay tuned :smiley:

**Comment by benbayard** [comment]
Awesome, loving the library so far. Are there any issues you need help tackling? I can take a look.
