### ISSUE TITLE
Converting circular structure to json

### ISSUE THREAD

**Issue by StrikeForceZero** [kamilmysliwiec/nest#88]
Is there a reason why middleware parameters have to be serialized? Is there alternative way to pass in a mysql connection object, for example?

https://github.com/kamilmysliwiec/nest/blob/master/src/common/utils/bind-resolve-values.util.ts#L11

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at node_modules\@nestjs\common\utils\bind-resolve-values.util.js:10:44
    at Array.map (native)
    at bindValuesToResolve (node_modules\@nestjs\core\middlewares\builder.js:37:39)
    at MiddlewareBuilder.ConfigProxy.forRoutes (node_modules\@nestjs\core\middlewares\builder.js:54:26)
    at CoreModule.<anonymous> (modules\core\index.ts:47:15)
    at Generator.next (<anonymous>)
    at fulfilled (modules\core\index.ts:10:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

**Comment by StrikeForceZero** [comment]
nvm, looks like you can inject components into middleware
